### ISSUE TITLE
findClosestDomain functionality using fuzzyset

### ISSUE THREAD

**Issue by kwnccc** [mailcheck/mailcheck#103]
Being aware of that this would be a totally different approach to the problem you solve, have you ever thought replacing findClosestDomain function with an implementation using fuzzyset.js (https://github.com/Glench/fuzzyset.js)?

Do you believe this is feasible implementation for mailcheck increasing its overall size at most by 3kb?

**Comment by derrickko** [comment]
Mailcheck supports custom string distance functions as stated here https://github.com/mailcheck/mailcheck/wiki/String-Distance-Algorithms .
