### ISSUE TITLE
bower install does not install newest version

### ISSUE THREAD

**Issue by leschirmeur** [mailcheck/mailcheck#104]
When running bower install --save mailcheck, the mailcheck.js file installed is not equal to the one currently accessible in Github. What is missing for example are the second level domains.

This is how the first lines of the file look like:

/*
 * Mailcheck https://github.com/mailcheck/mailcheck
 * Author
 * Derrick Ko (@derrickko)
 *
 * Released under the MIT License.
 *
 * v 1.1.0
 */

var Mailcheck = {
  domainThreshold: 4,
  topLevelThreshold: 3,

  defaultDomains: ["yahoo.com", "google.com", "hotmail.com", "gmail.com", "me.com", "aol.com", "mac.com",
    "live.com", "comcast.net", "googlemail.com", "msn.com", "hotmail.co.uk", "yahoo.co.uk",
    "facebook.com", "verizon.net", "sbcglobal.net", "att.net", "gmx.com", "mail.com", "outlook.com", "icloud.com"],

  defaultTopLevelDomains: ["co.jp", "co.uk", "com", "net", "org", "info", "edu", "gov", "mil", "ca"],

  run: function(opts) {...

END SNIPPET

Somehow it seems an older version of mailcheck is installed when using bower.

**Comment by johnotander** [comment]
I've encountered this issue as well.

Is it possible for a maintainer to add a git tag with the latest version so it will be installable through bower?

**Comment by weilu** [comment]
@johnotander I've tagged and published 1.1.1. See if that works for you?

**Comment by leschirmeur** [comment]
@weilu Thanks very much, works for me now!
