### ISSUE TITLE
npm install does not install newest version

### ISSUE THREAD

**Issue by Renetnielsen** [mailcheck/mailcheck#108]
As said in #104 i got exactly same problem, this time just through npm.

I can see he opened the issue 1. Of April, is there any eta. on when u actually will publish new versions to the package managers?

**Comment by weilu** [comment]
v1.1.1 published on npm with sha ee2eeea8935aee71e1c6a873dcfbe14384af2c21

**Comment by Renetnielsen** [comment]
Thank you very much!
