### ISSUE TITLE
Correcting for a misplaced period?

### ISSUE THREAD

**Issue by jgillman** [mailcheck/mailcheck#114]
We have a good chunk of users who must be in a rush to type their email address and we're seeing the period getting shifted over by one character. Is there a way this kind of correction could be accounted for?

Example:

```
myname@gmailc.om

Should be:
myname@gmail.com
```

**Comment by Trever123** [comment]
There is a JavaScript/jQuery plugin that seems quite popular that suggests when users have misspelt their email. You could try this:


https://github.com/mailcheck/mailcheck






Thanks,James

**Comment by weilu** [comment]
The library already provide the expected suggestion: https://github.com/mailcheck/mailcheck/commit/4ad175791da491f39ebb99c33e8ace9736372c56

**Comment by jgillman** [comment]
Sorry, I chose a bad example. A customer had the domain `rcn.com` but entered their email as `@rcnc.om`

Without explicitly adding `rcn.com` to `domains` is it possible for the pattern `c.om` to get corrected to `.com`?
