### ISSUE TITLE
Converted to PHP for backend checking

### ISSUE THREAD

**Issue by no1youknowz** [mailcheck/mailcheck#116]
Hey,

I needed something like this for backend processing, but for PHP.

I thought I would give back if anyone else needed it.  The class is for Codeigniter, but it's trivial to port to something else.

I've added the newer algorithm sift4 (simplest version) that could be used.

I'm doing a check on many thousands of domains, so essentially if I don't find a match I'll return the original email address.  Otherwise I will return the corrected emailaddress.

Your own use case may be different.  But then modify the public function.

Any comments / bugs / etc.  Let me know :+1: 

	class My_email_checker_funcs
	{
		function __construct()
		{
			$this->ci =& get_instance();

			$this->domainThreshold = 2;
			$this->secondLevelThreshold = 2;
			$this->topLevelThreshold = 2;

			$this->defaultDomains = array(
				'msn.com', 'bellsouth.net',
				'telus.net', 'comcast.net', 'optusnet.com.au',
				'earthlink.net', 'qq.com', 'sky.com', 'icloud.com',
				'mac.com', 'sympatico.ca', 'googlemail.com',
				'att.net', 'xtra.co.nz', 'web.de',
				'cox.net', 'gmail.com', 'ymail.com',
				'aim.com', 'rogers.com', 'verizon.net',
				'rocketmail.com', 'google.com', 'optonline.net',
				'sbcglobal.net', 'aol.com', 'me.com', 'btinternet.com',
				'charter.net', 'shaw.ca'
			);

			$this->defaultSecondLevelDomains = array(
				"yahoo", "hotmail", "mail", "live", "outlook", "gmx"
			);

	  		$this->defaultTopLevelDomains = array(
	  			"com", "com.au", "com.tw", "ca", "co.nz", "co.uk", "de",
			    "fr", "it", "ru", "net", "org", "edu", "gov", "jp", "nl", "kr", "se", "eu",
			    "ie", "co.il", "us", "at", "be", "dk", "hk", "es", "gr", "ch", "no", "cz",
	    		"in", "net", "net.au", "info", "biz", "mil", "co.jp", "sg", "hu"
	    	);
		}

		public function check($email)
		{
			$result = $this->suggest($this->encodeEmail($email), $this->defaultDomains, $this->defaultSecondLevelDomains, $this->defaultTopLevelDomains);

			if ($result['domain'] == "")
			{
				return $email;
			}
			else
			{
				$username = explode("@", $email)[0];
				$emailaddress = $username . "@" . $result['domain'];

				return $emailaddress;
			}
		}

		private function suggest($email, $domains, $secondLevelDomains, $topLevelDomains)
		{
			$email = strtolower($email);
			$emailParts = $this->splitEmail($email);

			$closestDomain = $this->findClosestDomain($emailParts['domain'], $domains, $this->domainThreshold);

			if ($closestDomain)
			{
				if ($closestDomain == $emailParts['domain'])
				{
					// The email address exactly matches one of the supplied domains; do not return a suggestion.
					return false;
				}
				else
				{
					// The email address closely matches one of the supplied domains; return a suggestion
					return array(
						"address" => $emailParts['address'],
						"domain" => $closestDomain,
						"full" => $emailParts["address"] . "@" . $closestDomain
					);
				}
			}

			// The email address does not closely match one of the supplied domains
			$closestSecondLevelDomain = $this->findClosestDomain($emailParts["secondLevelDomain"], $secondLevelDomains, $this->secondLevelThreshold);
			$closestTopLevelDomain = $this->findClosestDomain($emailParts["topLevelDomain"], $topLevelDomains, $this->topLevelThreshold);

			if ($emailParts["domain"])
			{
				$closestDomain = $emailParts["domain"];
				$rtrn = false;

				if($closestSecondLevelDomain && $closestSecondLevelDomain != $emailParts["secondLevelDomain"])
				{
					// The email address may have a mispelled second-level domain; return a suggestion
					$closestDomain = str_replace($emailParts["secondLevelDomain"], $closestSecondLevelDomain, $closestDomain);
					$rtrn = true;
				}

				if($closestTopLevelDomain && $closestTopLevelDomain != $emailParts["topLevelDomain"])
				{
					// The email address may have a mispelled top-level domain; return a suggestion
					$closestDomain = str_replace($emailParts["topLevelDomain"], $closestTopLevelDomain, $closestDomain);
					$rtrn = true;
				}

				if ($rtrn == true)
				{
					return array(
						"address" => $emailParts["address"],
						"domain" => $closestDomain,
						"full" => $emailParts["address"] . "@" . $closestDomain
					);
				}
			}

			/* The email address exactly matches one of the supplied domains, does not closely
			* match any domain and does not appear to simply have a mispelled top-level domain,
			* or is an invalid email address; do not return a suggestion.
			*/
			return false;
		}

		private function splitEmail($email)
		{
	    	$parts = explode("@", trim($email));

		    if (count($parts) < 2)
		    {
				return false;
		    }

		    for ($i = 0; $i < count($parts); $i++)
		    {
		      	if ($parts[$i] === '')
		      	{
		        	return false;
		      	}
		    }

		    $domain = array_pop($parts);
		    $domainParts = explode(".", $domain);
		    $sld = '';
		    $tld = '';

		    if (count($domainParts) == 0)
		    {
		      	// The address does not have a top-level domain
		      	return false;
		    }
		    else if (count($domainParts) == 1)
		    {
		      	// The address has only a top-level domain (valid under RFC)
		      	$tld = $domainParts[0];
		    }
		    else
		    {
		      	// The address has a domain and a top-level domain
		      	$sld = $domainParts[0];

			    for ($i = 1; $i < count($domainParts); $i++)
			    {
			    	$tld .= $domainParts[$i] . '.';
			    }

			    $tld = substr($tld, 0, strlen($tld) - 1);
		    }

		    return array(
				"topLevelDomain" => $tld,
				"secondLevelDomain" => $sld,
				"domain" => $domain,
				"address" => implode("@", $parts)
	    	);
		}

		private function findClosestDomain($domain, $domains, $threshold = null)
		{
			$threshold = $threshold == null ? $this->topLevelThreshold : $threshold;
			$dist = 0;
			$minDist = 99;
			$closestDomain = null;

			if (!$domain || !$domains)
			{
				return false;
			}

			for ($i = 0; $i < count($domains); $i++)
			{
				if ($domain === $domains[$i])
				{
					return $domain;
				}

				$dist = $this->sift4Distance($domain, $domains[$i]);

				if ($dist < $minDist)
				{
					$minDist = $dist;
					$closestDomain = $domains[$i];
				}
			}

			if ($minDist <= $threshold && $closestDomain !== null)
			{
				return $closestDomain;
			}
			else
			{
				return false;
			}
		}

		private function sift3Distance($s1, $s2)
		{
			// sift3: http://siderite.blogspot.com/2007/04/super-fast-and-accurate-string-distance.html
			if ($s1 == null || strlen($s1) === 0)
			{
				if ($s2 == null || strlen($s2) === 0)
				{
					return 0;
				}
				else
				{
					return strlen($s2);
				}
			}

			if ($s2 == null || strlen($s2) === 0)
			{
				return strlen(s1);
			}

			$c = 0;
			$offset1 = 0;
			$offset2 = 0;
			$lcs = 0;
			$maxOffset = 5;

			while (($c + $offset1 < strlen($s1)) && ($c + $offset2 < strlen($s2)))
			{
				if ($s1{$c + $offset1} == $s2{$c + $offset2})
				{
					$lcs++;
				}
				else
				{
					$offset1 = 0;
					$offset2 = 0;

					for ($i = 0; $i < $maxOffset; $i++)
					{
					  	if (($c + $i < strlen($s1)) && ($s1{$c + $i} == $s2{$c}))
					  	{
					    	$offset1 = $i;
					    	break;
					  	}
					  	if (($c + $i < strlen($s2)) && ($s1{$c} == $s2{$c + $i}))
					  	{
					    	$offset2 = $i;
					    	break;
					  	}
					}
				}

				$c++;
			}

			return (strlen($s1) + strlen($s2)) / 2 - $lcs;
		}

		private function sift4Distance($s1, $s2, $maxOffset = 0)
		{
			if (!$s1 || !strlen($s1))
			{
			    if (!$s2)
			    {
			        return 0;
			    }
			    return strlen($s2);
			}

			if (!$s2 || !strlen($s2))
			{
			    return $s1;
			}

			$l1 = strlen($s1);
			$l2 = strlen($s2);

			$c1 = 0;  //cursor for string 1
			$c2 = 0;  //cursor for string 2
			$lcss = 0;  //largest common subsequence
			$local_cs = 0; //local common substring

			while (($c1 < $l1) && ($c2 < $l2))
			{
			    if ($s1{$c1} == $s2{$c2})
			    {
			        $local_cs++;
			    }
			    else
			    {
			        $lcss += $local_cs;
			        $local_cs = 0;

			        if ($c1 != $c2)
			        {
			            $c1 = $c2 = max($c1,$c2); //using max to bypass the need for computer transpositions ('ab' vs 'ba')
			        }

			        for ($i = 0; $i < $maxOffset && ($c1 + $i < $l1 || $c2 + $i < $l2); $i++)
			        {
			            if (($c1 + $i < $l1) && ($s1{$c1 + $i} == $s2{$c2}))
			            {
			                $c1 += $i;
			                $local_cs++;
			                break;
			            }
			            if (($c2 + $i < $l2) && ($s1{$c1} == $s2{$c2 + $i}))
			            {
			                $c2 += $i;
			                $local_cs++;
			                break;
			            }
			        }
			    }

			    $c1++;
			    $c2++;
			}

			$lcss += $local_cs;

			return round(max($l1,$l2) - $lcss);
		}

		private function encodeEmail($email)
		{
	    	$result = urlencode($email);

	    	$result =  str_replace('%20', ' ', $email) .
		    	str_replace('%25', '%', $email) .
		    	str_replace('%5E', '^', $email) .
		    	str_replace('%60', '`', $email) .
		    	str_replace('%7B', '{', $email) .
		    	str_replace('%7C', '|', $email) .
		    	str_replace('%7D', '}', $email);

	    	return $result;
	    }
	}

**Comment by derrickko** [comment]
This looks awesome. Start a separate repo? I'd be happy to put it under the mailcheck Github org.
