### ISSUE TITLE
.org.xx is suggested as .org

### ISSUE THREAD

**Issue by williamdlees** [mailcheck/mailcheck#117]
Many countries have a .org subdomain, for example .org.uk, .org.au. Using one should not raise an error: it is very unlikely that someone would type .org.uk when they meant to type just .org, for example.

**Comment by jeremejazz** [comment]
:+1:

**Comment by weilu** [comment]
Good point. PRs are welcome

**Comment by williamdlees** [comment]
OK, you have a pull request :)
