### ISSUE TITLE
Adding other top level domains to the defaults

### ISSUE THREAD

**Issue by colin-c** [mailcheck/mailcheck#127]
On forms all over the web, this script seems to follow me around and has been behind many "Did you mean ...?" messages I encounter with my `.me` and `.io` addresses.

I understand that the default setting can be overridden, but it seems most sites just use this plugin out-of-the-box so it would be nice if they were included by default.

I suppose the risk of missing the case of users attempting to type `.de` or `.ie` may outweight the benefit here, but I'd like to hear others' thoughts on this.

**Comment by derrickko** [comment]
Mailcheck allows for custom domain lists; we'd actually recommend people overwrite the defaults to more relevant ones.
