### ISSUE TITLE
@gm, @gma and @gmai are suggested as @gr

### ISSUE THREAD

**Issue by pke** [mailcheck/mailcheck#129]
Using the default options any input of

```
name@gm
name@gma
name@gmai
```

is suggested with domain `gr`. Any idea why?

**Comment by caphun** [comment]
any update on this issue?

**Comment by pke** [comment]
@caphun nope. No idea whats going on. Maybe if #133 would be merged, the problem would go away. Or by removing the `.gr` domain.
