### ISSUE TITLE
getmailcheck.org domain has expired

### ISSUE THREAD

**Issue by szepeviktor** [mailcheck/mailcheck#154]
http://getmailcheck.org/

**Comment by ferreiro** [comment]
Disclaimer: This library is no longer maintained.

I rewrote it entirely and update it for 2022 and onward: https://github.com/ZooTools/email-spell-checker

- 💙 Written in TypeScript and removed jQuery
- ✅ Fixed a couple of bugs like [this](https://github.com/ZooTools/email-spell-checker/pull/3) or [this](https://github.com/ZooTools/email-spell-checker/pull/4)
- 🚀 Reduced bundle size to <2KB. 
- ✨ Update TLDs (69+) and added modern startup domains (like .io, .so, .xyz or .dev)
- 🙏 Implemented suggestions that people made in this repo that were ignored.

Link: https://github.com/ZooTools/email-spell-checker

Come check it out and give it a ⭐️ for the effort.

**Comment by szepeviktor** [comment]
Okay.
