### ISSUE TITLE
Synchronous use

### ISSUE THREAD

**Issue by LeoDupont** [mailcheck/mailcheck#166]
Hello!

I'd like to use mailcheck in a `filter` function, but I can't use a callback for this and I would need a synchronous result.

I saw the issue #52 and thought that was great!
But it looks like this feature got removed from the code at some point, and `Mailcheck.run` always returns `undefined`.

Is there any mean of using mailcheck synchronously? 
What are the benefits of using callbacks instead of a return?

**Comment by lemcii** [comment]
works fine synchronously here

**Comment by LeoDupont** [comment]
It works fine indeed.

I guess I was leaving the `suggested` callback in the `run` method's options while testing the library and didn't realise it should not be provided in order for it to return something.

In case someone runs into the same problem as me, here is a summary:

```javascript
var mailcheck = require('mailcheck');

var result, testmail = 'test@hotnail.com';

// === With a 'suggested' callback ===

result = mailcheck.run({
  email: testmail,
  suggested: (res) => {
    // res contains the suggestion
  }
}); // result is undefined

// === Without callback ===

result = mailcheck.run({
  email: testmail,
}); // result contains the suggestion
```
