### ISSUE TITLE
Mailcheck suggest to crop anything after .com to .com only

### ISSUE THREAD

**Issue by ejmedina** [mailcheck/mailcheck#30]
When email like "user@notInListOfKnownDomains.com.ar" mailcheck will suggest to crop ".ar"
The suggestion, I think,  should be made only when the domain softmatches to one domain in the list of the known domains.

**Comment by WorksOfBarry** [comment]
Confirmed.

I have a .co.uk email address, but it likes to suggest .com instread.

**Comment by viralpickaxe** [comment]
Confirmed aswell

**Comment by derrickko** [comment]
This is tweakable through your preferred string distance function https://github.com/mailcheck/mailcheck/wiki/String-Distance-Algorithms
