### ISSUE TITLE
Failure to specify a TLD results in an invalid suggestion

### ISSUE THREAD

**Issue by kmillerdevx3** [mailcheck/mailcheck#37]
Entry of certain invalid content results in the suggestion of domains such as "@com", "@edu", etc.

This seems to include many entries where a top-level domain is not specified.  For example, entering "a@b" suggests "a@com"; entering "a@ad" suggests "a@edu", etc.

Certain items are caught, such as "@ao", which suggests "@aol.com".

**Comment by derrickko** [comment]
Already fixed. Use `domains`, `secondLevelDomains` and `topLevelDomains`.
