### ISSUE TITLE
Any three letter domain is suggested as aol.com

### ISSUE THREAD

**Issue by osCMattiFinn** [mailcheck/mailcheck#88]
As per the title, any three letter domain gets suggested as aol.com.

Is there a way to make it less sensitive?  eg. ail.com would be valid for an aol.com suggestion since the i and o keys are adjacent.

**Comment by morganwdavis** [comment]
cox.con is another example that gets converted to aol.com.

**Comment by derrickko** [comment]
You can use 

```
domains: domains,                       // optional
secondLevelDomains: secondLevelDomains, // optional
topLevelDomains: topLevelDomains,       // optional
```
