### ISSUE TITLE
Use with Require.JS

### ISSUE THREAD

**Issue by ball-hayden** [mailcheck/mailcheck#90]
I'm trying to use mailcheck with Require.JS.

Currently, I have a shim around Mailcheck (which works with other modules):

```
require.config
  shim:
    mailcheck:
      exports: "Mailcheck"
```

This works fine in development (the Mailcheck global is there), but once I run it through the r.js optimizer things break.
I don't know a huge amount about the r.js optimizer, but it looks like the optimizer wraps all the libraries that are included in an anonymous function. Since Mailcheck is declared as `var Mailcheck = `, it is local to the wrapped function, which means it is no longer globally accessible.

Would you consider either:
a) Supporting requirejs (using something like http://stackoverflow.com/a/17954882/1322410)
b) Attaching Mailcheck to the window object (if it is defined) so that it is still globally accessible.

Thank you.

**Comment by ball-hayden** [comment]
I've gone ahead and added requirejs support (https://github.com/SparkSeat/mailcheck/commit/c152fc1cb858b8596280304305d9a5d63fd2021e)
I'm happy to open this as a PR if you would be interested in merging it.

**Comment by weilu** [comment]
Sounds good! Go ahead :)

**Comment by ball-hayden** [comment]
PR opened. Thanks.
