### ISSUE TITLE
Default configuration is not allowing @hotmail.com

### ISSUE THREAD

**Issue by justinperkins** [mailcheck/mailcheck#96]
I cannot get @hotmail.com addresses to come through with the default configuration, despite the existence of "hotmail" in the defaultSecondLevelDomains collection ...

```
> Mailcheck.run({email:'test@hotmail.com', suggested: function(suggestion){ console.log(suggestion.full)}})
> test@gmail.com
```

**Comment by houmark** [comment]
Same for me. Not sure what is a working workaround.

**Comment by derrickko** [comment]
Please re-open if this is still an issue!
