### ISSUE TITLE
valid secondLevelDomain + topLevelDomain combination still gets corrected to "likely" choice from domains list.

### ISSUE THREAD

**Issue by hjwp** [mailcheck/mailcheck#97]
Taking the example straight from the README.md:

```javascript
var domains = ['gmail.com', 'aol.com'];
var secondLevelDomains = ['hotmail']
var topLevelDomains = ["com", "net", "org"];
```

then a user entering "myaddress@hotmail.com" will have "myaddress@gmail.com" suggested to them. 

Surely that can't be the desired behaviour?

http://jsfiddle.net/8habg633/

**Comment by derrickko** [comment]
This could be due to a string comparison issue. @kevinhughes27 did you come across this behavior in your second level domain implementation?

**Comment by kevinhughes27** [comment]
currently it checks all the *full domains* first so if one of them is under the threshold it will return the match and not check the second level and top level domains at all. I suspect you are using a very loose threshold for top level domains, if you tighten that up then it should not correct hotmail.com to gmail.com

**Comment by kevinhughes27** [comment]
check the sift3 distance between those 2 strings

**Comment by hjwp** [comment]
I'm not sure if I'm being asked to try something here?   But if y'all want a suggestion, it seems to me that if the user's input matches a valid second-level+top-level combination, then the full domains list should just be ignored?

**Comment by kevinhughes27** [comment]
mailcheck has always treated *full domains* with priority. Sorry I wasn't super clear my point was if check the sift3 distance between those strings using the function inside mailcheck you'll see it is under your threshold.

**Comment by hjwp** [comment]
I see, thanks.  Supposing I didn't want that*, and wanted to say that full domains are checked only if 2nd-level+tld doesn't match.  I presume I'd have to fork the repo?  Any chance of a quick pointer for where to look to make the change?

* and, naturally, being a developer, I think that anyone who has different requirements from my own is *objectively wrong*

**Comment by kevinhughes27** [comment]
lol so true.

If you want to swap it around check out the mailcheck.js file and look for the `suggest` function https://github.com/mailcheck/mailcheck/blob/master/src/mailcheck.js#L39

You'll be able to see that it checks full domains first and then second and tld etc. If you swap the order here you can get the behaviour you want. Let us know how it works out!

**Comment by hjwp** [comment]
sounds good.  are there tests anywhere?

**Comment by kevinhughes27** [comment]
yep, there is a suite under the tests directory. Just unit tests though the project doesn't have a huge set of data to test on

**Comment by weilu** [comment]
@hjwp Is this resolved?

**Comment by derrickko** [comment]
Please re-open if this is still an issue!
